/* DB Diagram link : https://dbdiagram.io/d/SQL-PROJECT-67351f26e9daa85aca5eeac1 */

CREATE TABLE "transportation_means" (
  "id_mdt" char(3) PRIMARY KEY,
  "line_name" varchar(32),
  "max_capacity" integer,
  "travel_time" integer
);

CREATE TABLE "line" (
  "id" integer PRIMARY KEY,
  "code" varchar(3),
  "transportation_mode_id" integer
);

CREATE TABLE "station" (
  "id" integer PRIMARY KEY,
  "id_station" integer,
  "station_name" varchar(64),
  "station_municipality" varchar(64),
  "transportation_mode_id" integer,
  "zone_id" integer,
  "municipality_id" integer
);

CREATE TABLE "municipality" (
  "id" integer PRIMARY KEY,
  "municipality_name" varchar(64)
);

CREATE TABLE "zone" (
  "zone_number" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zone_name" varchar(32),
  "zone_price" decimal
);

CREATE TABLE "line_Zone" (
  "line_id" int,
  "zone_id" int
);

CREATE TABLE "line_Station" (
  "line_id" int,
  "station_id" int,
  "position" int
);

CREATE TABLE "user" (
  "id" integer PRIMARY KEY,
  "lastname" varchar(32),
  "firstname" varchar(32),
  "email" varchar(128),
  "phone_number" char(10),
  "address" varchar(128),
  "zipcode" char(5),
  "municipality_id" integer
);

CREATE TABLE "employee" (
  "id" integer PRIMARY KEY,
  "login" varchar(20),
  "user_id" integer
);

CREATE TABLE "contract" (
  "id" integer PRIMARY KEY,
  "employeed_at" timestamp,
  "leaved_at" timestamp,
  "service_id" integer,
  "employee_id" integer
);

CREATE TABLE "service" (
  "id" integer PRIMARY KEY,
  "name" varchar(50),
  "reduction_percentage" integer
);

CREATE TABLE "service_rights" (
  "id" integer PRIMARY KEY,
  "service_reduc" integer,
  "description" text,
  "service_id" integer
);

CREATE TABLE "journey" (
  "id" integer PRIMARY KEY,
  "user_id" integer,
  "entry_time" timestamp,
  "entry_station_id" integer,
  "exit_time" timestamp,
  "exit_station_id" integer
);

CREATE TABLE "package" (
  "code" char(5) PRIMARY KEY,
  "name" varchar(32),
  "price_per_month" float NOT NULL,
  "duration_month" integer NOT NULL,
  "min_zone" integer,
  "max_zone" integer
);

CREATE TABLE "subscription" (
  "id" integer PRIMARY KEY,
  "date_sub" timestamp NOT NULL,
  "iban" varchar(34) NOT NULL,
  "adress_proof" boolean NOT NULL,
  "users_id" integer NOT NULL,
  "package_code" char(5) NOT NULL,
  "status" enum(Registered,Pending,Incomplete) NOT NULL
);

CREATE TABLE "bill" (
  "id" integer PRIMARY KEY,
  "user_id" integer NOT NULL,
  "subscription_id" integer,
  "total_price" float NOT NULL
);

ALTER TABLE "transportation_means" ADD FOREIGN KEY ("id_mdt") REFERENCES "line" ("transportation_mode_id");

ALTER TABLE "transportation_means" ADD FOREIGN KEY ("id_mdt") REFERENCES "station" ("transportation_mode_id");

ALTER TABLE "zone" ADD FOREIGN KEY ("zone_number") REFERENCES "station" ("zone_id");

ALTER TABLE "municipality" ADD FOREIGN KEY ("id") REFERENCES "station" ("municipality_id");

ALTER TABLE "line" ADD FOREIGN KEY ("id") REFERENCES "line_Zone" ("line_id");

ALTER TABLE "zone" ADD FOREIGN KEY ("zone_number") REFERENCES "line_Zone" ("zone_id");

ALTER TABLE "line" ADD FOREIGN KEY ("id") REFERENCES "line_Station" ("line_id");

ALTER TABLE "station" ADD FOREIGN KEY ("id") REFERENCES "line_Station" ("station_id");

ALTER TABLE "municipality" ADD FOREIGN KEY ("id") REFERENCES "user" ("municipality_id");

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "employee" ("user_id");

ALTER TABLE "service" ADD FOREIGN KEY ("id") REFERENCES "contract" ("service_id");

ALTER TABLE "employee" ADD FOREIGN KEY ("id") REFERENCES "contract" ("employee_id");

ALTER TABLE "service" ADD FOREIGN KEY ("id") REFERENCES "service_rights" ("service_id");

ALTER TABLE "station" ADD FOREIGN KEY ("id") REFERENCES "journey" ("entry_station_id");

ALTER TABLE "station" ADD FOREIGN KEY ("id") REFERENCES "journey" ("exit_station_id");

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "journey" ("user_id");

ALTER TABLE "zone" ADD FOREIGN KEY ("zone_number") REFERENCES "package" ("max_zone");

ALTER TABLE "zone" ADD FOREIGN KEY ("zone_number") REFERENCES "package" ("min_zone");

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "subscription" ("users_id");

ALTER TABLE "package" ADD FOREIGN KEY ("code") REFERENCES "subscription" ("package_code");

ALTER TABLE "user" ADD FOREIGN KEY ("id") REFERENCES "bill" ("user_id");
