/* DB Diagram link : https://dbdiagram.io/d/SQL-PROJECT-67351f26e9daa85aca5eeac1 */

CREATE TABLE "moyens_de_transport" (
  "id_mdt" char(3) PRIMARY KEY,
  "line_name" varchar(32),
  "max_capacity" integer,
  "travel_time" integer
);

CREATE TABLE "ligne" (
  "id" integer PRIMARY KEY,
  "code" varchar(3),
  "moyen_de_transport_id" integer
);

CREATE TABLE "station" (
  "id" integer PRIMARY KEY,
  "id_station" integer,
  "station_name" varchar(64),
  "station_commune" varchar(64),
  "moyen_de_transport_id" integer,
  "zone_id" integer,
  "commune_id" integer
);

CREATE TABLE "commune" (
  "id" integer PRIMARY KEY,
  "commune_name" varchar(64)
);

CREATE TABLE "zone" (
  "zone_number" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zone_name" varchar(32),
  "zone_price" decimal
);

CREATE TABLE "Ligne_Zone" (
  "ligne_id" int,
  "zone_id" int
);

CREATE TABLE "Ligne_Station" (
  "ligne_id" int,
  "station_id" int,
  "position" int
);

CREATE TABLE "utilisateur" (
  "id" integer PRIMARY KEY,
  "lastname" varchar(32),
  "firstname" varchar(32),
  "email" varchar(128),
  "phone_number" char(10),
  "address" varchar(128),
  "zipcode" char(5),
  "commune_id" integer
);

CREATE TABLE "employé" (
  "id" integer PRIMARY KEY,
  "login" varchar(20),
  "utilisateur_id" integer
);

CREATE TABLE "contrat" (
  "id" integer PRIMARY KEY,
  "employed_at" timestamp,
  "leaved_at" timestamp,
  "service_id" integer,
  "employe_id" integer
);

CREATE TABLE "service" (
  "id" integer PRIMARY KEY,
  "name" varchar(50),
  "reduction_percentage" integer
);

CREATE TABLE "service_droit" (
  "id" integer PRIMARY KEY,
  "service_reduc" integer,
  "description" text,
  "service_id" integer
);

CREATE TABLE "trajet" (
  "id" integer PRIMARY KEY,
  "utilisateur_id" integer,
  "entry_time" timestamp,
  "entry_station_id" integer,
  "exit_time" timestamp,
  "exit_station_id" integer
);

CREATE TABLE "forfait" (
  "id" integer PRIMARY KEY,
  "code" char(5),
  "name" varchar(32),
  "price_per_month" float NOT NULL,
  "duration_month" integer NOT NULL,
  "min_zone" integer,
  "max_zone" integer
);

CREATE TABLE "abonnement" (
  "id" integer PRIMARY KEY,
  "starting_date" timestamp NOT NULL,
  "iban" varchar(34) NOT NULL,
  "adress_proof" boolean NOT NULL,
  "utilisateurs_id" integer NOT NULL,
  "forfait_id" integer NOT NULL,
  "statut" enum(Registered,Pending,Incomplete) NOT NULL
);

CREATE TABLE "facture" (
  "id" integer PRIMARY KEY,
  "utilisateur_id" integer NOT NULL,
  "abonnement_id" integer,
  "total_price" float NOT NULL
);

ALTER TABLE "moyens_de_transport" ADD FOREIGN KEY ("id_mdt") REFERENCES "ligne" ("moyen_de_transport_id");

ALTER TABLE "moyens_de_transport" ADD FOREIGN KEY ("id_mdt") REFERENCES "station" ("moyen_de_transport_id");

ALTER TABLE "zone" ADD FOREIGN KEY ("zone_number") REFERENCES "station" ("zone_id");

ALTER TABLE "commune" ADD FOREIGN KEY ("id") REFERENCES "station" ("commune_id");

ALTER TABLE "ligne" ADD FOREIGN KEY ("id") REFERENCES "Ligne_Zone" ("ligne_id");

ALTER TABLE "zone" ADD FOREIGN KEY ("zone_number") REFERENCES "Ligne_Zone" ("zone_id");

ALTER TABLE "ligne" ADD FOREIGN KEY ("id") REFERENCES "Ligne_Station" ("ligne_id");

ALTER TABLE "station" ADD FOREIGN KEY ("id") REFERENCES "Ligne_Station" ("station_id");

ALTER TABLE "commune" ADD FOREIGN KEY ("id") REFERENCES "utilisateur" ("commune_id");

ALTER TABLE "utilisateur" ADD FOREIGN KEY ("id") REFERENCES "employé" ("utilisateur_id");

ALTER TABLE "service" ADD FOREIGN KEY ("id") REFERENCES "contrat" ("service_id");

ALTER TABLE "employé" ADD FOREIGN KEY ("id") REFERENCES "contrat" ("employe_id");

ALTER TABLE "service" ADD FOREIGN KEY ("id") REFERENCES "service_droit" ("service_id");

ALTER TABLE "station" ADD FOREIGN KEY ("id") REFERENCES "trajet" ("entry_station_id");

ALTER TABLE "station" ADD FOREIGN KEY ("id") REFERENCES "trajet" ("exit_station_id");

ALTER TABLE "utilisateur" ADD FOREIGN KEY ("id") REFERENCES "trajet" ("utilisateur_id");

ALTER TABLE "zone" ADD FOREIGN KEY ("zone_number") REFERENCES "forfait" ("max_zone");

ALTER TABLE "zone" ADD FOREIGN KEY ("zone_number") REFERENCES "forfait" ("min_zone");

ALTER TABLE "utilisateur" ADD FOREIGN KEY ("id") REFERENCES "abonnement" ("utilisateurs_id");

ALTER TABLE "forfait" ADD FOREIGN KEY ("id") REFERENCES "abonnement" ("forfait_id");

ALTER TABLE "utilisateur" ADD FOREIGN KEY ("id") REFERENCES "facture" ("utilisateur_id");
